require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TimersController do

  # This should return the minimal set of attributes required to create a valid
  # Timer. As you add validations to Timer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "time" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all timers as @timers" do
      timer = Timer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:timers).should eq([timer])
    end
  end

  describe "GET show" do
    it "assigns the requested timer as @timer" do
      timer = Timer.create! valid_attributes
      get :show, {:id => timer.to_param}, valid_session
      assigns(:timer).should eq(timer)
    end
  end

  describe "GET new" do
    it "assigns a new timer as @timer" do
      get :new, {}, valid_session
      assigns(:timer).should be_a_new(Timer)
    end
  end

  describe "GET edit" do
    it "assigns the requested timer as @timer" do
      timer = Timer.create! valid_attributes
      get :edit, {:id => timer.to_param}, valid_session
      assigns(:timer).should eq(timer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Timer" do
        expect {
          post :create, {:timer => valid_attributes}, valid_session
        }.to change(Timer, :count).by(1)
      end

      it "assigns a newly created timer as @timer" do
        post :create, {:timer => valid_attributes}, valid_session
        assigns(:timer).should be_a(Timer)
        assigns(:timer).should be_persisted
      end

      it "redirects to the created timer" do
        post :create, {:timer => valid_attributes}, valid_session
        response.should redirect_to(Timer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved timer as @timer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timer.any_instance.stub(:save).and_return(false)
        post :create, {:timer => { "time" => "invalid value" }}, valid_session
        assigns(:timer).should be_a_new(Timer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timer.any_instance.stub(:save).and_return(false)
        post :create, {:timer => { "time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested timer" do
        timer = Timer.create! valid_attributes
        # Assuming there are no other timers in the database, this
        # specifies that the Timer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Timer.any_instance.should_receive(:update_attributes).with({ "time" => "MyString" })
        put :update, {:id => timer.to_param, :timer => { "time" => "MyString" }}, valid_session
      end

      it "assigns the requested timer as @timer" do
        timer = Timer.create! valid_attributes
        put :update, {:id => timer.to_param, :timer => valid_attributes}, valid_session
        assigns(:timer).should eq(timer)
      end

      it "redirects to the timer" do
        timer = Timer.create! valid_attributes
        put :update, {:id => timer.to_param, :timer => valid_attributes}, valid_session
        response.should redirect_to(timer)
      end
    end

    describe "with invalid params" do
      it "assigns the timer as @timer" do
        timer = Timer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timer.any_instance.stub(:save).and_return(false)
        put :update, {:id => timer.to_param, :timer => { "time" => "invalid value" }}, valid_session
        assigns(:timer).should eq(timer)
      end

      it "re-renders the 'edit' template" do
        timer = Timer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timer.any_instance.stub(:save).and_return(false)
        put :update, {:id => timer.to_param, :timer => { "time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested timer" do
      timer = Timer.create! valid_attributes
      expect {
        delete :destroy, {:id => timer.to_param}, valid_session
      }.to change(Timer, :count).by(-1)
    end

    it "redirects to the timers list" do
      timer = Timer.create! valid_attributes
      delete :destroy, {:id => timer.to_param}, valid_session
      response.should redirect_to(timers_url)
    end
  end

end
